name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.bumpversion.cfg'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]' && github.actor != 'github-actions'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bumpversion
    - name: Configure Git
      run: |
        git config --global user.email "sinanartun@gmail.com"
        git config --global user.name "Sinan Artun"
    - name: Bump version and commit
      run: |
        bumpversion patch
        git push
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*